### ISSUE TITLE
这里面怎么加header的

### ISSUE THREAD

**Issue by runtu666** [webman-tech/swagger#10]
![image](https://github.com/user-attachments/assets/27a12d31-ac38-4cbd-a9fa-5a7453e517e3)

我这种注解写法里面怎么加请求头？有没有参考的文档

**Comment by krissss** [comment]
请求头指什么，header 传参吗？

如果是请求参数的话，如下：

```php
#[OA\Post](
    parameters: [
          new OA\HeaderParameter(name: 'Authorization', description: 'token')
    ],
)
```

如果想定义全局的 header 拦截的话：https://zircote.github.io/swagger-php/guide/cookbook.html#default-security-scheme-for-all-endpoints

**Comment by runtu666** [comment]
ok
