### ISSUE TITLE
swagger 主题更换

### ISSUE THREAD

**Issue by wjinwandalaohu** [webman-tech/swagger#8]
swagger 文档的主题更换，这个默认版本的主题太老了，但是我在app.php去设置swagger_ui没生效，能告诉我具体原因嘛？作者大大

**Comment by krissss** [comment]
提供下复现方式

**Comment by wjinwandalaohu** [comment]
<?php
use OpenApi\Annotations as OA;
return [
    'enable' => true,
    'global_route' => [
        'enable' => true,
        'register_webman_route' => true,
        'route_prefix' => '/docs',  // Swagger UI 路由前缀，例如 http://localhost:8787/docs
    ],
    'host_forbidden' => [
        'enable' => false,
        'host_white_list' => [],
    ],
    'scan' => [
        base_path() . '/app',  // 扫描路径
    ],
    'swagger_ui' => [
        'display' => true,  // 启用 Swagger UI
        'custom_path' => '/public/swagger-ui', // 使用 Material 主题
//        'displayOperationId' => true,  // 显示操作 ID
//        'defaultModelsExpandDepth' => -1, // 不显示 Models
//        'defaultModelExpandDepth' => 1, // 默认显示一层
//        'docExpansion' => 'none', // 折叠所有操作
//        'layout' => 'BaseLayout', // 使用基本布局
//        'deepLinking' => true, // 深度链接
//        'filter' => true, // 启用过滤器搜索
//        'showExtensions' => true, // 显示扩展信息
//        'showCommonExtensions' => true, // 显示常用扩展信息
    ],
    'openapi_doc' => [
        'openapi' => '3.0.0',  // 默认的 OpenAPI 版本
        'info' => [
            'title' => 'AC Controller API',
            'version' => '1.0.0',
            'description' => 'API documentation for the AC Controller system.',
            'contact' => [
                'email' => 'support@yourdomain.com',
            ],
            'license' => [
                'name' => 'MIT',
                'url' => 'https://opensource.org/licenses/MIT',
            ],
        ],
        'servers' => [
            [
                'url' => 'http://localhost',
                'description' => 'Local server'
            ],
        ],
        'output' => base_path() . '/public/swagger.json',  // 输出文件位置
        'scan' => [
            base_path() . '/app',  // 确保这里的路径是正确的
        ],
        'modify' => static function(OA\OpenApi $openApi) {
            $openApi->info->title = 'My App';
            $openApi->info->version = '1.0.0';
            $openApi->servers = [
                new OA\Server(['url' => '/', 'description' => 'localhost']),
            ];
        },
    ],
];

**Comment by wjinwandalaohu** [comment]
![Uploading 微信图片_20240921114531.png…]()
