### ISSUE TITLE
怎么自动校验schema

### ISSUE THREAD

**Issue by runtu666** [webman-tech/swagger#9]
<img width="1149" alt="image" src="https://github.com/user-attachments/assets/249f930d-029d-4761-8360-10f3246926ee">
这里的create和validator 是怎么来的？文档并没有体现这一块

**Comment by krissss** [comment]
已更新 readme

需要继承 `WebmanTech\Swagger\SchemaAnnotation\BaseSchema`，漏了

validator 是 laravel，webman 中可以使用 [webman-tech/laravel-validation](https://github.com/webman-tech/laravel-validation)

**Comment by runtu666** [comment]
好的，顺便问一下，怎么在注解中定义校验 @krissss

**Comment by krissss** [comment]
不能定义过于复杂的校验，只能校验基础的，比如必填，数据类型

详见 https://github.com/webman-tech/swagger/blob/11eaffca204f9b1d2be131f1d7a4ee8f6805ec66/tests/Unit/SchemaAnnotation/DTO/ClassInfoDTOTest.php#L123

**Comment by krissss** [comment]
BaseSchema 下可以覆盖 validationExtraRules 方法来自定义额外的验证

比如：

```php
<?php

use OpenApi\Attributes as OA;
use WebmanTech\Swagger\SchemaAnnotation\BaseSchema;

#[OA\Schema(required: ['name', 'age'])]
class TestSchema extends BaseSchema {
    #[OA\Property(description: '名称', example: 'webman')]
    public string $name = '';
    #[OA\Property(description: '年龄', example: 5)]
    public int $age = 0;
    #[OA\Property(description: '备注', example: 'xxx')]
    public string $remark = '';

    protected function validationExtraRules(): array
    {
        return [
            'name' => 'size:12',
        ];
    }
}
```

**Comment by runtu666** [comment]
> BaseSchema 下可以覆盖 validationExtraRules 方法来自定义额外的验证
> 
> 比如：
> 
> ```
> <?php
> 
> use OpenApi\Attributes as OA;
> use WebmanTech\Swagger\SchemaAnnotation\BaseSchema;
> 
> #[OA\Schema(required: ['name', 'age'])]
> class TestSchema extends BaseSchema {
>     #[OA\Property(description: '名称', example: 'webman')]
>     public string $name = '';
>     #[OA\Property(description: '年龄', example: 5)]
>     public int $age = 0;
>     #[OA\Property(description: '备注', example: 'xxx')]
>     public string $remark = '';
> 
>     protected function validationExtraRules(): array
>     {
>         return [
>             'name' => 'size:12',
>         ];
>     }
> }
> ```

**Comment by runtu666** [comment]
> BaseSchema 下可以覆盖 validationExtraRules 方法来自定义额外的验证
> 
> 比如：
> 
> ```
> <?php
> 
> use OpenApi\Attributes as OA;
> use WebmanTech\Swagger\SchemaAnnotation\BaseSchema;
> 
> #[OA\Schema(required: ['name', 'age'])]
> class TestSchema extends BaseSchema {
>     #[OA\Property(description: '名称', example: 'webman')]
>     public string $name = '';
>     #[OA\Property(description: '年龄', example: 5)]
>     public int $age = 0;
>     #[OA\Property(description: '备注', example: 'xxx')]
>     public string $remark = '';
> 
>     protected function validationExtraRules(): array
>     {
>         return [
>             'name' => 'size:12',
>         ];
>     }
> }
> ```

哦，那这种就比较方便了

**Comment by runtu666** [comment]
@krissss  顺便帮我看下这个issue https://github.com/webman-tech/swagger/issues/10

你们有交流群吗，可以拉我一下吗

**Comment by krissss** [comment]
![IMG_20241011_145833.png](https://github.com/user-attachments/assets/4550976a-a5e0-4855-8352-a1b06db53f16)

你可以加我微信，暂时没有交流群
